// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherApi.Persistence.EF;

#nullable disable

namespace WeatherApi.Persistence.EF.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20250525100941_3rd")]
    partial class _3rd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("SQ_Hilo_City");

            modelBuilder.Entity("WeatherApi.Domain.Entities.Cities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("WeatherApi.Domain.Entities.Cities.Station", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Station");
                });

            modelBuilder.Entity("WeatherApi.Domain.Entities.WeatherReport.WeatherReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("StationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("WeatherReports");
                });

            modelBuilder.Entity("WeatherApi.Domain.Entities.Cities.City", b =>
                {
                    b.OwnsOne("WeatherApi.Domain.ValueObjects.GeoLocation", "location", b1 =>
                        {
                            b1.Property<long>("CityId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.Navigation("location")
                        .IsRequired();
                });

            modelBuilder.Entity("WeatherApi.Domain.Entities.Cities.Station", b =>
                {
                    b.HasOne("WeatherApi.Domain.Entities.Cities.City", "City")
                        .WithMany("Stations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WeatherApi.Domain.ValueObjects.GeoLocation", "Location", b1 =>
                        {
                            b1.Property<long>("StationId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("StationId");

                            b1.ToTable("Station");

                            b1.WithOwner()
                                .HasForeignKey("StationId");
                        });

                    b.Navigation("City");

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("WeatherApi.Domain.Entities.WeatherReport.WeatherReport", b =>
                {
                    b.HasOne("WeatherApi.Domain.Entities.Cities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WeatherApi.Domain.ValueObjects.WeatherData", "WeatherData", b1 =>
                        {
                            b1.Property<long>("WeatherReportId")
                                .HasColumnType("bigint");

                            b1.Property<int>("humidity")
                                .HasColumnType("int");

                            b1.Property<double>("pressure")
                                .HasColumnType("float");

                            b1.Property<double>("temperature")
                                .HasColumnType("float");

                            b1.Property<double>("windDirection")
                                .HasColumnType("float");

                            b1.Property<double>("windSpeed")
                                .HasColumnType("float");

                            b1.HasKey("WeatherReportId");

                            b1.ToTable("WeatherReports");

                            b1.WithOwner()
                                .HasForeignKey("WeatherReportId");
                        });

                    b.Navigation("Station");

                    b.Navigation("WeatherData")
                        .IsRequired();
                });

            modelBuilder.Entity("WeatherApi.Domain.Entities.Cities.City", b =>
                {
                    b.Navigation("Stations");
                });
#pragma warning restore 612, 618
        }
    }
}
